version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/yourdbname
      JWT_SECRET: your_jwt_secret
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 15m
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 7d
      EMAIL_USER: your_email_user
      EMAIL_PASSWORD: your_email_password
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
